<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Core\Module'                         => __DIR__ . '/Module.php',
  'Core\Comms\Email'                    => __DIR__ . '/src/Core/Comms/Email.php',
  'Core\Controller\ApiController'       => __DIR__ . '/src/Core/Controller/ApiController.php',
  'Debug'                               => __DIR__ . '/src/Core/Debug.php',
  'Core\Entity\Base'                    => __DIR__ . '/src/Core/Entity/Base.php',
  'Registry'                            => __DIR__ . '/src/Core/Registry.php',
  'Core\Service\Base'                   => __DIR__ . '/src/Core/Service/Base.php',
  'Core\Service\Response'               => __DIR__ . '/src/Core/Service/Response.php',
  'Core\Service\ServiceInterface'       => __DIR__ . '/src/Core/Service/ServiceInterface.php',
  'Session'                             => __DIR__ . '/src/Core/Session.php',
  'Core\Utility\DataActionNotification' => __DIR__ . '/src/Core/Utility/DataActionNotification.php',
  'Core\Utility\Doctrine'               => __DIR__ . '/src/Core/Utility/Doctrine.php',
  'Core\Utility\Validator'              => __DIR__ . '/src/Core/Utility/Validator.php',
);
