<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'WinningNumbers\Module'                                       => __DIR__ . '/Module.php',
  'WinningNumbers\Controller\WinningNumbersController'          => __DIR__ . '/src/WinningNumbers/Controller/WinningNumbersController.php',
  'WinningNumbers\Entity\WinningNumbers'                        => __DIR__ . '/src/WinningNumbers/Entity/WinningNumbers.php',
  'WinningNumbers\Service\WinningNumbers'                       => __DIR__ . '/src/WinningNumbers/Service/WinningNumbers.php',
);
