<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Randomizer\Module'                                   => __DIR__ . '/Module.php',
  'Randomizer\Controller\RandomizerController'          => __DIR__ . '/src/Randomizer/Controller/RandomizerController.php',
  'Randomizer\Entity\RandomizerConfig'                  => __DIR__ . '/src/Randomizer/Entity/RandomizerConfig.php',
  'Randomizer\Fixture\RandomizerConfig'                 => __DIR__ . '/src/Randomizer/Fixture/RandomizerConfig.php',
  'Randomizer\Service\Randomizer'                       => __DIR__ . '/src/Randomizer/Service/Randomizer.php',
);
